connections and targets
faradayio/sdk_docs pull request #22
Opened 2022-05-05 20:12 UTC by blakew

let's try this again

2022-05-09 10:24 UTC, emk requested changes

2022-05-09 10:24 UTC, emk commented on static/api.interfaces.yml
> -    #     required: true
Yeah, all this should be removed because it's simply incorrect, using `Scope#Post` instead of `Scope#MergePatch`, etc. And commented-out code is fair game for deletion, unless it's part of a comment showing how _not_ to do something.

2022-05-09 10:24 UTC, emk commented on static/api.interfaces.yml
> +        paranoid_quoting:
Is "paranoid" a good choice of name for our public API? Let's take this discussion internal, please.

2022-05-09 10:24 UTC, emk commented on static/api.interfaces.yml
> +              The S3 object key inside of the bucket. For example, path/to/my/file.csv. If you enable gzip, we recommend you add .gz to the end.
I notice that we often wind up duplicating the name of the option as the first line of the description. This seems like it might be an artifact of just straight exporting the database to OpenAPI YAML? Can we fix this somehow at the database layer, or in our scripts?

2022-05-09 10:24 UTC, emk commented on static/vannevar.yml
> +---
A++ comment. :-)

2022-05-10 18:09 UTC, blakew commented on static/api.interfaces.yml
> +              Whether to always quote CSV cells, even if they don't contain quotes. Some systems require this.
changed

2022-05-10 18:09 UTC, blakew commented on static/api.interfaces.yml
> +        paranoid_quoting:
changed

2022-05-10 18:10 UTC, blakew commented on static/api.interfaces.yml
> +      description: A group of people, specified in one of a variety of ways.
There was an issue with openapi-interfaces that required this modification. Can we revert once the new version is released?

2022-05-10 18:32 UTC, blakew commented on static/api.interfaces.yml
> +              The S3 object key inside of the bucket. For example, path/to/my/file.csv. If you enable gzip, we recommend you add .gz to the end.
condensed, thanks.

2022-05-10 19:34 UTC, merged