Add Snowflake role option
faradayio/sdk_docs pull request #28
Opened 2022-05-12 14:53 UTC by prithajnath

2022-05-12 14:59 UTC, blakew requested changes

2022-05-12 14:59 UTC, blakew commented on static/api.interfaces.yml
> +          required: true
this is not consistent with the vannevar changes, which replaces `user` with `role`

2022-05-12 15:04 UTC, prithajnath commented on static/api.interfaces.yml
> +          required: true
@blakew The `user` slug was duplicated in vannevar. That's why it's replacing one of them with `role`. We need both `role` and `user`

2022-05-12 18:20 UTC, merged

2022-05-13 13:54 UTC, zebapy commented
@prithajnath  fyi something about the package-lock changes caused ci failure (granted it was on a mostly unused ci task)